- hosts: all
  vars:
       - image: idndevops/web_nginx
  tasks:
       - name: install python-docker di centos
         yum:
           name: "{{ item }}"
           state: present
         loop:
             - python3
             - python3-docker
         when: ansible_facts['os_family'] == 'RedHat'
       - name: install python-docker di ubuntu
         apt:
           name: "{{ item }}"
           state: present
         loop:
             - python3
             - python3-docker
         when: ansible_facts['os_family'] == 'Debian'                                                                                                                         
       - name: pull image
         docker_image:
           name: "{{ image }}"
           state: present
           force: yes
       - name: run container
         docker_container:
           name: web_nginx_ansible  
           image: "{{ image }}"  
           state: started
           published_ports:
                   - 10000:80 
           recreate: yes
